Add: Javaを追加

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,7 +18,7 @@ jobs:
 
       - name: Setup environment
         uses: ./.github/actions/setup-environment
-      - run: npm run electron:build_pnever
+      # - run: npm run electron:build_pnever
 
       - name: Setup keystore
         shell: bash
@@ -26,6 +26,19 @@ jobs:
           cat - | base64 -d > keystore.jks <<EOF
           ${{ secrets.ANDROID_KEYSTORE_DATA }}
           EOF
+          if [ -s keystore.jks ]; then
+            echo "Created keystore.jks"
+            $SHA256=$(sha256sum keystore.jks | cut -d ' ' -f 1)
+            echo "SHA256: $SHA256"
+          else
+            echo "Failed to create keystore.jks"
+            echo "Have you set ANDROID_KEYSTORE_DATA, ANDROID_KEYSTORE_PASS, ANDROID_KEYSTORE_ALIAS and ANDROID_KEYSTORE_ALIAS_PASS?"
+            exit 1
+          fi
+      - name: Setup java
+        uses: actions/setup-java@v1
+        with:
+          java-version: 1.8
       - name: Setup Android SDK
         uses: android-actions/setup-android@v2
       - name: Build Android
